import {
  tailand,
  tyrkey,
  indonesia,
  georgia,
  oae,
  tailandnoun,
  tyrkeynoun,
  indonesianoun,
  georgianoun,
} from "./variables.js";

const cardsData = [
  {
    title: "Жилой комплекс Riviera Santa Monica",
    class: "Премиум",
    location: "Таиланд, Паттайя, Джомтьен",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "29 - 325 м²",
    price: "62 000 $",
    about: "34 этажа, 446 квартиры",
    plan: "1, 2, 3 - комнатные, пентхаусы",
    deadline: "2025-2028 г.",
    sea: "1 км",
    developer: "The Riviera Group Thailand",
    description:
      "Комплекс расположен в престижном районе с развитой и близостью к пляжу, а из окон открываются виды на море. Удобное расположение: всего в нескольких минутах езды до пляжа, ключевых объектов инфраструктуры и рядом с основными дорожными развязками. Комплекс идеально подходит как для комфортного отдыха, так и для инвестиций - сдачи в аренду или перепродажи",
    id: "block1",
    pay: "рассрочка",
    benefit: "24%",
    income: "5 400 $",
    btntitle: "Куда вам отправить презентацию The Riviera Santa Monica?",
    btnsub: "Презентация The Riviera Santa Monica",
    images: [
      "./images/RivetaSantaMonica/RivieraSantaMonica1.webp",
      "./images/RivetaSantaMonica/RivieraSantaMonica3.webp",
      "./images/RivetaSantaMonica/RivieraSantaMonica4.webp",
      "./images/RivetaSantaMonica/RivieraSantaMonica5.webp",
    ],
  },
  {
    title: "The Panora Phuket",
    class: "Премиум",
    location: "Таиланд, Пхукет, район Раваи",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "36 м² до 326 м²",
    price: "12 779 780 ₽ до 65 613 080 ₽",
    about: "5 корпусов, 200 апартаментов в продаже",
    plan: "1+1, 2+1, 3+1",
    deadline: "4 квартал 2026 г.",
    sea: "1 км",
    developer: "The Panora Development",
    description:
      "Современный ЖК с панорамными видами на природу и просторными апартаментами. На территории предусмотрены бассейны с морской водой, спа-зоны и фитнес-центры. Рядом находятся песчаные пляжи, рестораны с местной кухней и ТЦ. Идеальное место для тех, кто ценит комфорт, уединение и близость к развитой инфраструктуре. Отличный выбор для жизни и отдыха!",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 555 956 ₽",
    income: "1 022 382 ₽",
    btntitle: "Куда вам отправить презентацию The Panora Phuket?",
    btnsub: "Презентация The Panora Phuket",
    images: [
      "./images/The Panora Phuket/1.webp",
      "./images/The Panora Phuket/2.webp",
      "./images/The Panora Phuket/3.webp",
      "./images/The Panora Phuket/4.webp",
      "./images/The Panora Phuket/5.webp",
      "./images/The Panora Phuket/6.webp",
      "./images/The Panora Phuket/7.webp",
      "./images/The Panora Phuket/8.webp",
      "./images/The Panora Phuket/9.webp",
      "./images/The Panora Phuket/10.webp",
    ],
  },
  {
    title: "Hyde Heritage Thonglor",
    class: "Элитный",
    location: "Таиланд, Бангкок, район Тонглор",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "40 - 244 м²",
    price: "25 257 000 - 153 779 376 ₽",
    about: "45 этажей, 311 апартаментов",
    plan: "1+1, 2+1, 3+1",
    deadline: "Сдан.",
    developer: "Grande Asset Hotels and Property",
    description:
      "Высокие потолки и большие окна от пола до потолка пропускают много естественного света и позволяют наслаждаться потрясающим видом на город днем ​​и ночью. Бассейн на крыше, сауна, тренажерный зал, симулятор гольфа, сад/зона для барбекю, детская площадка, парковка, магазин и ресторан на территории отеля.",
    id: "block1",
    pay: "рассрочка",
    benefit: "5 051 400 ₽",
    income: "от 1 515 420 ₽",
    btntitle: "Куда вам отправить презентацию Hyde Heritage Thonglor?",
    btnsub: "Презентация Hyde Heritage Thonglor",
    images: [
      "./images/Hyde Heritage Thonglor/1.webp",
      "./images/Hyde Heritage Thonglor/2.webp",
      "./images/Hyde Heritage Thonglor/3.webp",
      "./images/Hyde Heritage Thonglor/4.webp",
      "./images/Hyde Heritage Thonglor/5.webp",
      "./images/Hyde Heritage Thonglor/6.webp",
      "./images/Hyde Heritage Thonglor/7.webp",
      "./images/Hyde Heritage Thonglor/8.webp",
    ],
  },
  {
    title: "Andaman Riviera",
    class: "Комфорт+",
    location: "Таиланд, Пхукет, район Банг Тао",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "33 - 250 м²",
    price: "13 640 000 ₽",
    about: "7 этажей, 165 апартаментов",
    plan: "1+1, 2+1",
    deadline: "4 квартал 2026 г.",
    sea: "500 м",
    developer: "Andaman Riviera Construction",
    description:
      "Элитный жилой комплекс, расположен в 5 минутах от пляжа Банг-Тао. В пешей доступности престижные пляжные клубы, ТЦ Porto de Phuket, рынок Mango market. До международного аэропорта Утапао 20 минут на автомобиле. Бассейн, детская площадка, фитнес, охрана",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 555 956 ₽",
    income: "954 800 ₽",
    btntitle: "Куда вам отправить презентацию Andaman Riviera?",
    btnsub: "Презентация Andaman Riviera",
    images: [
      "./images/Andaman Riviera/1.webp",
      "./images/Andaman Riviera/2.webp",
      "./images/Andaman Riviera/3.webp",
      "./images/Andaman Riviera/4.webp",
      "./images/Andaman Riviera/5.webp",
    ],
  },

  {
    title: "Комплекс вилл Botanica The Valley",
    class: "Элитный",
    location: "Таиланд, Пхукет, район Лагуна",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: " 200 - 450 м²",
    price: "182 997 269 ₽",
    about: "комплекс вилл",
    plan: "3+1, 4+1,5+1",
    deadline: "Октябрь 2025 г.",
    sea: "1,5 км",
    developer: "Botanica Luxury Villas",
    description:
      "Потрясающий панорамный вид на горы 360 ° с каждой виллы. Комплекс включает виллы с индивидуальными планировками, площадью 625 - 1488 м² и большими террасами, личным бассейном, ландшафтным садом и парковкой. Каждая вилла отличается стильным дизайном и качественной отделкой.",
    id: "block1",
    pay: "рассрочка",
    benefit: "36 599 453 ₽",
    income: "10 979 836 ₽ ",
    btntitle:
      "Куда вам отправить презентацию комплекса вилл Botanica The Valley?",
    btnsub: "Презентация комплекса вилл Botanica The Valley",
    images: [
      "./images/Botanica The Valley/1.webp",
      "./images/Botanica The Valley/2.webp",
      "./images/Botanica The Valley/3.webp",
      "./images/Botanica The Valley/4.webp",
      "./images/Botanica The Valley/5.webp",
    ],
  },
  {
    title: "The Crest Santora",
    class: "Премиум",
    location: "Таиланд, Хуа Хин, район Као Такиаб",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "65 - 160 м²",
    price: "14,315,230 - 27,787,700 ₽",
    about: "10 зданий, 4 этажа, 181 апартамент",
    plan: "1+1, 2+1, 3+1",
    deadline: "Май 2025 г.",
    sea: "200 м",
    developer: "SC Asset",
    description:
      "Инфраструктура: Бассейн, фитнес, спа, ресторан, пляжный доступ The Crest Santora — это изысканный кондоминиум, предлагающий уникальный опыт стильной и современной жизни. Обладая идеальным сочетанием роскоши и удобства, он обеспечивает спокойную обстановку и максимальный комфорт и безопасность.",
    id: "block1",
    pay: "рассрочка",
    benefit: "-",
    income: "-",
    btntitle: "Куда вам отправить презентацию The Crest Santora?",
    btnsub: "Презентация The Crest Santora",
    images: [
      "./images/The Crest Santora/1.webp",
      "./images/The Crest Santora/2.webp",
      "./images/The Crest Santora/3.webp",
      "./images/The Crest Santora/4.webp",
      "./images/The Crest Santora/5.webp",
    ],
  },
  {
    title: "Dusit Grand Park 2",
    class: "Комфорт",
    location: "Таиланд, Паттайя, район Джомтьен",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "35 - 70 м²",
    price: "6,735,200-13,470,400 ₽",
    about: "8 корпусов, 5 этажей",
    plan: "студии, 1+1, 2+1",
    deadline: "Сдан",
    sea: "1,2 км",
    developer: "Dusit Group",
    description:
      "Воплощение современного курортного жилья класса люкс, расположенного в престижном районе. В проекте — 8-этажные жилые корпуса, открытый бассейн и общественные пространства. Каждая квартира оснащена премиальной отделкой и укомплектована качественной мебелью.",
    id: "block1",
    pay: "рассрочка",
    benefit: "1 347 040 ₽",
    income: "404 112 ₽",
    btntitle: "Куда вам отправить презентацию Dusit Grand Park 2?",
    btnsub: "Презентация Dusit Grand Park 2",
    images: [
      "./images/Dusit Grand Park 2/1.webp",
      "./images/Dusit Grand Park 2/2.webp",
      "./images/Dusit Grand Park 2/3.webp",
      "./images/Dusit Grand Park 2/4.webp",
      "./images/Dusit Grand Park 2/5.webp",
      "./images/Dusit Grand Park 2/6.webp",
      "./images/Dusit Grand Park 2/7.webp",
      "./images/Dusit Grand Park 2/8.webp",
      "./images/Dusit Grand Park 2/9.webp",
      "./images/Dusit Grand Park 2/10.webp",
    ],
  },
  {
    title: "Ayana Luxury Villas",
    class: "Премиум",
    location: "Таиланд, Пхукет, район Таланг",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "221 - 469 м²",
    price: "56 459 890 - 157 141 788 ₽",
    plan: "3+1, 4+1, 5+1",
    deadline: "4 квартал 2026, есть сданные",
    sea: "5 км",
    developer: "TH Group",
    description:
      "В элитном комплексе дома будут окружены горами, озёрами и зеленью лесов. Виллы с отделкой под ключ, собственным бассейном и придомовым участком. Комплекс будет выдержан в минималистичном стиле. В зависимости от типа дома предусмотрен гараж на 2 или 3 машины.",
    id: "block1",
    pay: "рассрочка",
    benefit: "11 291 978 ₽",
    income: "3 387 593 ₽",
    btntitle:
      "Куда вам отправить презентацию комплекса вилл Ayana Luxury Villas?",
    btnsub: "Презентация комплекса вилл Ayana Luxury Villas",
    images: [
      "./images/Ayana Luxury Villas/1.webp",
      "./images/Ayana Luxury Villas/2.webp",
      "./images/Ayana Luxury Villas/3.webp",
      "./images/Ayana Luxury Villas/4.webp",
      "./images/Ayana Luxury Villas/5.webp",
      "./images/Ayana Luxury Villas/6.webp",
      "./images/Ayana Luxury Villas/7.webp",
      "./images/Ayana Luxury Villas/8.webp",
      "./images/Ayana Luxury Villas/9.webp",
      "./images/Ayana Luxury Villas/10.webp",
    ],
  },

  {
    title: "Жилой комплекс The Momentum",
    class: "Элитный",
    location: "Таиланд, Пхукет, район Тхаланг",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "36 – 376 м²",
    price: "11 786 432 – 155 019 372 ₽",
    plan: "студии, 1+1, 2+1",
    deadline: "3 квартал 2027 г.",
    sea: "1 км",
    developer: "Serene Innovations and Developments",
    description:
      "Элитный ЖК находится на острове Пхукет в Таиланде. Здесь оборудуют бассейн, тренажёрный зал, спа-центр. Можно приобрести виллу с собственным бассейном, с панорамными окнами и балконами. Поблизости с  ЖК будут кафе, рестораны, аптека, отделение банка.",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 357 286 ₽",
    income: "707 185 ₽",
    btntitle: "Куда вам отправить презентацию ЖК The Momentum?",
    btnsub: "Презентация ЖК The Momentum",
    images: [
      "./images/The Momentum/1.webp",
      "./images/The Momentum/2.webp",
      "./images/The Momentum/3.webp",
      "./images/The Momentum/4.webp",
      "./images/The Momentum/5.webp",
      "./images/The Momentum/6.webp",
      "./images/The Momentum/7.webp",
      "./images/The Momentum/8.webp",
    ],
  },
  {
    title: "Жилой комплекс Laya Resort",
    class: "Элитный",
    location: "Таиланд, Пхукет, район Банг Тао",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "24 – 75 м²",
    price: "9 263 461 – 36 641 371 ₽",
    plan: "1+1, 2+1",
    deadline: "4 квартал 2025, есть сданные",
    sea: "350 м.",
    developer: "Alliance corp.",
    description:
      "Роскошный курортный комплекс расположен на одном из самых престижных участков Пхукета, всего в 350 м. от пляжа Bang Tao (Layan), который славится своей красотой и чистотой. Инфраструктура включает в себя бассеийны, фитнес центр, детскую зону, сад на крыше, коворкинг и многое другое.",
    id: "block1",
    pay: "рассрочка",
    benefit: "1 852 692 ₽ ",
    income: "555 807 ₽ ",
    btntitle: "Куда вам отправить презентацию ЖК Laya Resort?",
    btnsub: "Презентация ЖК Laya Resort",
    images: [
      "./images/Laya Resort/1.webp",
      "./images/Laya Resort/2.webp",
      "./images/Laya Resort/3.webp",
      "./images/Laya Resort/4.webp",
      "./images/Laya Resort/5.webp",
      "./images/Laya Resort/6.webp",
      "./images/Laya Resort/7.webp",
      "./images/Laya Resort/8.webp",
      "./images/Laya Resort/9.webp",
      "./images/Laya Resort/10.webp",
    ],
  },
  {
    title: "Жилой комплекс Layan Verde",
    class: "Элитный",
    location: "Таиланд, Пхукет, район Банг Тао",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "37 – 638 м²",
    price: "16 822 294 – 322 524 300 ₽",
    plan: "премиум, люкс, пентхаусы",
    deadline: "2 квартал 2027, есть сданные",
    sea: "200 м.",
    developer: "Layan Verde",
    description:
      "Layan Verde находится на западном побережье, в районе Банг Тао, всего в 2-х минутах от белоснежного песчаного пляжа Лаян. Планировки апартаментов эргономичны, а также оборудованы всеми передовыми технологиями будущего: системой Smart Home, климат-контролем, энергосберегающими оборудования.",
    id: "block1",
    pay: "рассрочка",
    benefit: "3 364 458 ₽",
    income: "1 177 592 ₽",
    btntitle: "Куда вам отправить презентацию ЖК Layan Verde?",
    btnsub: "Презентация ЖК Layan Verde",
    images: [
      "./images/Layan Verde/1.webp",
      "./images/Layan Verde/2.webp",
      "./images/Layan Verde/3.webp",
      "./images/Layan Verde/4.webp",
      "./images/Layan Verde/5.webp",
      "./images/Layan Verde/6.webp",
      "./images/Layan Verde/7.webp",
      "./images/Layan Verde/8.webp",
      "./images/Layan Verde/9.webp",
    ],
  },
  {
    title: "Ayana Luxury Villas",
    class: "Премиум",
    location: "Таиланд, Пхукет, район Таланг",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    area: "221 - 469 м²",
    price: "6,735,200-13,470,400 ₽",
    plan: "3+1, 4+1, 5+1",
    deadline: "4 квартал 2026 г., есть сданные",
    sea: "5 км",
    developer: "TH Group",
    description:
      "В элитном комплексе дома будут окружены горами, озёрами и зеленью лесов. Виллы с отделкой под ключ, собственным бассейном и придомовым участком. Комплекс будет выдержан в минималистичном стиле. В зависимости от типа дома предусмотрен гараж на 2 или 3 машины.",
    id: "block1",
    pay: "рассрочка",
    benefit: "11 291 978 ₽",
    income: "3 387 593 ₽",
    btntitle:
      "Куда вам отправить презентацию Комплекса вилл Ayana Luxury Villas?",
    btnsub: "Презентация Комплекса вилл Ayana Luxury Villas",
    images: [
      "./images/Ayana Luxury Villas/1.webp",
      "./images/Ayana Luxury Villas/2.webp",
      "./images/Ayana Luxury Villas/3.webp",
      "./images/Ayana Luxury Villas/4.webp",
      "./images/Ayana Luxury Villas/5.webp",
      "./images/Ayana Luxury Villas/6.webp",
      "./images/Ayana Luxury Villas/7.webp",
      "./images/Ayana Luxury Villas/8.webp",
      "./images/Ayana Luxury Villas/9.webp",
      "./images/Ayana Luxury Villas/10.webp",
    ],
  },
  {
    title: "Жилой комплекс Ozdence Hill Luxury Residence",
    class: "Премиум",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Алания, Каргыджак",
    area: "от 69 - 491 м²",
    price: "310 000 $",
    about: "138 квартир",
    plan: "студии, 1, 2, 3, 4 - комнатные",
    deadline: "2 квартал 2026 г.",
    developer: "OZDENCE GROUP",
    description:
      "Özdence Hill Luxury Residence — это роскошный жилой комплекс, который предлагает своим собственникам широкий спектр удобств и возможностей для комфортного проживания. В резиденции расположенытеннисные и баскетбольные площадки, мини-гольф, бассейн с водным парком, рестораны и бары высокого класса.",
    id: "block1",
    pay: "рассрочка",
    benefit: "30%",
    income: "22 400 €",
    btntitle: "Куда вам отправить презентацию Ozdence Hill Luxury Residence?",
    btnsub: "Презентация Ozdence Hill Luxury Residence",

    images: [
      "/images/Ozdence/0.webp",
      "/images/Ozdence/1.webp",
      "/images/Ozdence/2.webp",
      "/images/Ozdence/3.webp",
      "/images/Ozdence/4.webp",
      "/images/Ozdence/5.webp",
    ],
  },
  {
    title: "Sur Yapi Antalya Park",
    class: "Комфорт",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Анталья, район Кепез",
    area: "47 - 226 м²",
    price: "12 603 411 - 58 168 678 ₽",
    about: "общая площадь 1,3 млн. м², 19 000 квартир",
    plan: "1+1, 2+1, 3+1, 4+1",
    deadline: "Сдан",
    sea: "6 км",
    developer: "SurYapi Antalya",
    description:
      "Основной идеей проекта является применение инноваций, среди которых стоит отметить современные материалы, полностью светодиодное освещение улиц с датчиками движения, доступный Wi-Fi. Инфраструктура включает в себя обширные парковые зоны, торговые и развлекательные центры, музей, современные больницы и мечети.",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 520 682 ₽",
    income: "1 008 272 ₽",
    btntitle: "Куда вам отправить презентацию Sur Yapi Antalya Park?",
    btnsub: "Презентация Sur Yapi Antalya Park",

    images: [
      "/images/Sur Yapi Antalya Park/1.webp",
      "/images/Sur Yapi Antalya Park/2.webp",
      "/images/Sur Yapi Antalya Park/3.webp",
      "/images/Sur Yapi Antalya Park/4.webp",
      "/images/Sur Yapi Antalya Park/5.webp",
    ],
  },
  {
    title: "Oksa Oba Residence",
    class: "Комфорт+",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Аланья, район Оба",
    area: "46 - 145 м²",
    price: "14 628 000 ₽",
    about: "4 этажа, 31 апартаментов",
    plan: "1+1, 2+1, 3+1",
    deadline: "Август 2025",
    sea: "800 м",
    developer: "Oksa Insaat",
    description:
      "Стильный жилой комплекс с современной архитектурой и оригинальным дизайном интерьеров. Апартаменты и пентхаусы, доступные в Oxo Oba Residence, сдаются в чистовой отделке, полностью готовые для заселения и меблировки. Есть бассейн, хаммам, фитнес, детская зона и парковка.",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 925 600 ₽",
    income: "1 170 240 ₽",
    btntitle: "Куда вам отправить презентацию Oksa Oba Residence?",
    btnsub: "Презентация Oksa Oba Residence",

    images: [
      "/images/Oksa Oba Residence/1.webp",
      "/images/Oksa Oba Residence/2.webp",
      "/images/Oksa Oba Residence/3.webp",
    ],
  },
  {
    title: "Отель Angsana Oceanview Residences",
    class: "Люкс",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    location: "Таиланд, Пхукет, Чернгталай",
    area: "209 - 395 м²",
    price: "1 300 000 $",
    about: "3 здания, 7 этажей, 149 квартир",
    plan: "2, 3 - комнатные, апартаменты",
    deadline: "2025 г., есть сданные",
    sea: "800 м.",
    developer: "Laguna Property",
    description:
      "Каждое жильё оснащено бассейном с захватывающими видами на озеро и пляж. В резиденциях есть гостиная, спальня с ванной и выходом на террасу. В пентхаусах на нижнем уровне жилые помещения, а на верхнем большая развлекательная терраса и бассейн. Удобства и инфраструктура: SPA- и фитнес-центр, ресторан и бар, прямой доступ к пляжу. Покупатели получают право пользования апартаментами.",
    id: "block1",
    pay: "рассрочка",
    benefit: "522 000 $",
    income: "130 565 $",
    btntitle: "Куда вам отправить презентацию Angsana Oceanview Residences?",
    btnsub: "Презентация Angsana Oceanview Residences",

    images: [
      "/images/Angsana/1.webp",
      "/images/Angsana/2.webp",
      "/images/Angsana/3.webp",
      "/images/Angsana/4.webp",
      "/images/Angsana/5.webp",
      "/images/Angsana/6.webp",
      "/images/Angsana/7.webp",
      "/images/Angsana/8.webp",
      "/images/Angsana/9.webp",
    ],
  },

  {
    title: "SkyLine",
    category: `${indonesia}`,
    noun: `${indonesianoun}`,
    location: "Индонезия, о. Бали, г. Убудт",
    area: "от 93 - 132 м²",
    price: "170 000 $",
    about: "13 вилл: 11 вилл с 1 спальней и 2 виллы с 2 спальнями.",
    deadline: "4 квартал 2025 г.",
    sea: "800 м.",
    developer: "The Future Estate",
    description:
      "Виллы располагаются в тихом месте с живописным видом на рисовые поля. Виллы полностью меблированы и оборудованы всем необходимым для отдыха и сдачи в аренду. Виллы расположены на высоте 200 м. над уровнем моря, что обеспечивает комфортный климат. Владельцам предоставляется возможность самостоятельно использовать виллу или сдать её в аренду через управляющую компанию.",
    id: "block1",
    pay: "рассрочка",
    benefit: " 67 900 $",
    income: "38 420 $",
    btntitle: "Куда вам отправить презентацию виллы SkyLine?",
    btnsub: "Презентация виллы SkyLine",

    images: [
      "/images/SkyLine/1.webp",
      "/images/SkyLine/2.webp",
      "/images/SkyLine/3.webp",
      "/images/SkyLine/5.webp",
      "/images/SkyLine/6.webp",
      "/images/SkyLine/7.webp",
      "/images/SkyLine/8.webp",
      "/images/SkyLine/9.webp",
    ],
  },
  {
    title: "Отель Radisson Blu Residences",
    class: "Премиум",
    category: `${georgia}`,
    noun: `${georgianoun}`,
    location: "Грузия, г. Батуми, Гонио-Квариати",
    area: "32 - 88 м²",
    price: "127 374 $ до 310 576 $",
    about: "26 этажей, 576 апартаментов",
    plan: "студии, 1, 2 - комнатные",
    deadline: "декабрь 2025 г.",
    sea: "20 м.",
    developer: "Next Group",
    description:
      "Располагается отель на побережье с легким доступом к самому лучшему пляжу и панорамными видами на зеленые горы. В комплексе есть фитнес-центр, частный пляж, лаунж-бар, конференц-зал, открытый бассейн с подогревом, подземная парковка. Покупая апартаменты в Radisson Blu Residences, вы получаете полное право собственности на недвижимость с возможностью дальнейшей перепродажи или сдачи в аренду.",
    id: "block1",
    pay: "рассрочка",
    benefit: "12 737 $",
    income: "8 400 $",
    btntitle: "Куда вам отправить презентацию отеля Radisson Blu Residences?",
    btnsub: "Презентация отеля Radisson Blu Residences",

    images: [
      "/images/Radisson Blu Residences/1.webp",
      "/images/Radisson Blu Residences/2.webp",
      "/images/Radisson Blu Residences/3.webp",
      "/images/Radisson Blu Residences/4.webp",
      "/images/Radisson Blu Residences/5.webp",
      "/images/Radisson Blu Residences/6.webp",
      "/images/Radisson Blu Residences/7.webp",
      "/images/Radisson Blu Residences/12.webp",
    ],
  },
  {
    title: "Wyndham Grand Residences Batumi Gonio. Aqua",
    class: "Элитный",
    category: `${georgia}`,
    noun: `${georgianoun}`,
    location: "Грузия, г. Батуми, Гонио-Квариати",
    area: "31 - 151 м",
    price: "241 592 $ до 1 205 184 $",
    about: "20 этажей",
    plan: "студии, 1, 2, 3 - комнатные",
    deadline: "1 квартал 2025 г.",
    sea: "400 м.",
    developer: "European Village",
    description:
      "Покупка недвижимости в этом отеле - это инвестиция в высококачественный образ жизни и будущее. Апартаменты с панорамными видами на море и город. Владельцы получают доступ к услугам международного гостиничного оператора Wyndham. Близость к пляжам, культурным объектам и деловым центрам делает эти апартаменты идеальным вариантом как для отдыха, так и для аренды.",
    id: "block1",
    pay: "рассрочка",
    benefit: "72 477 $",
    income: "33 822 $",
    btntitle:
      "Куда вам отправить презентацию Wyndham Grand Residences Batumi Gonio. Aqua?",
    btnsub: "Презентация Wyndham Grand Residences Batumi Gonio. Aqua",

    images: [
      "/images/Wyndham Grand Residences Batumi Gonio. Aqua/6.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Aqua/3.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Aqua/4.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Aqua/1.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Aqua/2.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Aqua/5.webp",
    ],
  },
  {
    title: "Wyndham Grand Residences Batumi Gonio. Family Club",
    class: "Элитный",
    category: `${georgia}`,
    noun: `${georgianoun}`,
    location: "Грузия, г. Батуми, Гонио-Квариати",
    area: "37 - 166 м²",
    price: "198 586 $ до 1 199 680 $",
    about: "5 этажей",
    plan: "пентхаус, студии, 1, 2 - комнатные",
    deadline: "2025 г.",
    sea: "400 м.",
    developer: "European Village",
    description:
      "Проект предлагает уютные апартаменты с продуманными планировками. Семейная атмосфера поддерживается наличием детских площадок, зон отдыха и бассейнов. Близость к морю, паркам и образовательным учреждениям делает проживание здесь удобным и приятным. Отель занимает площадь в 15 000 м² и состоит из 90 объектов, что делает его привлекательным для туристов в любое время года.",
    id: "block1",
    pay: "рассрочка",
    benefit: "59 575 $",
    income: "27 802 $",
    btntitle:
      "Куда вам отправить презентацию Wyndham Grand Residences Batumi Gonio. Family Club?",
    btnsub: "Презентация Wyndham Grand Residences Batumi Gonio. Family Club",

    images: [
      "/images/Wyndham Grand Residences Batumi Gonio. Family Club/1.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Family Club/2.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Family Club/3.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Family Club/4.webp",
    ],
  },
  {
    title: "Wyndham Grand Residences Batumi Gonio. Riviera",
    class: "Элитный",
    category: `${georgia}`,
    noun: `${georgianoun}`,
    location: "Грузия, г. Батуми, Гонио-Квариати",
    area: "130 - 150 м²",
    price: "609 180 $ до 702 900 $",
    about: "40 трехэтажных таунхаусов",
    plan: "пентхаус, студии, 1, 2 - комнатные",
    deadline: "1 квартал 2025 г.",
    sea: "800 м.",
    developer: "European Village",
    description:
      "Приобретение недвижимости в этом комплексе — это шанс стать владельцем жилья премиум-класса в одном из лучших районов Батуми. Проект располагается на первой линии у моря. Здесь предлагаются апартаменты с современным дизайном и высококачественной отделкой. Резиденты смогут насладиться инфраструктурой комплекса, включающей бассейны, СПА-зоны, фитнес-центры и рестораны.",
    id: "block1",
    pay: "рассрочка",
    benefit: "182 754 $",
    income: "79 193 $",
    btntitle:
      "Куда вам отправить презентацию Wyndham Grand Residences Batumi Gonio. Riviera?",
    btnsub: "Презентация Wyndham Grand Residences Batumi Gonio. Riviera",

    images: [
      "/images/Wyndham Grand Residences Batumi Gonio. Riviera/5.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Riviera/1.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Riviera/2.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Riviera/3.webp",
      "/images/Wyndham Grand Residences Batumi Gonio. Riviera/4.webp",
    ],
  },
  {
    title: "Wyndham Grand Batumi Gonio Villas",
    class: "Элитный",
    category: `${georgia}`,
    noun: `${georgianoun}`,
    location: "Грузия, г. Батуми, Гонио-Квариати",
    area: "173 м²",
    price: "703 195 $",
    about: "виллы, 2 этажа",
    plan: "пентхаус, студии, 1, 2 - комнатные",
    deadline: "2 квартал 2025 г.",
    sea: "400 м.",
    developer: "European Village",
    description:
      "Проект предлагает апартаменты с высококачественной отделкой и видами на море и горы.Расположение обеспечивает легкий доступ к пляжам, ТЦ и развлекательным заведениям. В инфраструктуру входит: бассейны, SPA, фитнес-центры и рестораны и многое другое. Управляющая компания Wyndham гарантирует высокий уровень сервиса и максимальную отдачу от инвестиций.",
    id: "block1",
    pay: "рассрочка",
    benefit: "210 958 $",
    income: "98 447 $",
    btntitle:
      "Куда вам отправить презентацию Wyndham Grand Batumi Gonio Villas?",
    btnsub: "Презентация Wyndham Grand Batumi Gonio Villas",

    images: [
      "/images/Wyndham Grand Batumi Gonio Villas/1.webp",
      "/images/Wyndham Grand Batumi Gonio Villas/2.webp",
      "/images/Wyndham Grand Batumi Gonio Villas/3.webp",
    ],
  },
  {
    title: "Апарт-отель Next Collection",
    class: "Премиум",
    category: `${georgia}`,
    noun: `${georgianoun}`,
    location: "Грузия, г. Батуми, Махинджаури",
    area: "34 - 248 м²",
    price: " 65 550 $ до 605 833 $",
    about: "15 этажей, 750 апартаментов",
    plan: "студии, 1, 2 - комнатные",
    deadline: "Июнь 2026 г.",
    sea: "50 м.",
    developer: "Next Group",
    description:
      "Это апарт-отель с собственным пляжем и инфраструктурой: 5 бассейнов, 3 ресторана, 2 лобби-бара, SPA- и фитнес-центры, теннисный корт, конференц-зал, 3 лаундж-зоны и многое другое. Проект предлагает жилые пространства с высококачественной отделкой и великолепными видами. Собственники могут использовать апартаменты для личного отдыха или сдачи в аренду.",
    id: "block1",
    pay: "рассрочка, ипотека",
    benefit: "20 000 $",
    income: "6 555 $",
    btntitle: "Куда вам отправить презентацию Апарт-отеля Next Collection?",
    btnsub: "Презентация Апарт-отеля Next Collection",

    images: [
      "/images/Next Collection/1.webp",
      "/imagesNext Collection/2.webp",
      "/images/Next Collection/3.webp",
      "/images/Next Collection/4.webp",
      "/images/Next Collection/5.webp",
    ],
  },
  {
    title: "Жилой комплекс NEXT CORAL",
    class: "Премиум",
    category: `${oae}`,
    noun: `${oae}`,
    location: "ОАЭ, Дубай",
    area: "47 - 188 м²",
    price: "238 000 $",
    about: "10 этажей, 80 апартаментов",
    plan: "студия, 1, 2, 3 - комнатные",
    deadline: "декабрь 2026 г.",
    sea: "50 м.",
    developer: "Next Realty",
    description:
      "Next Coral - комплекс апартаментов премиум-класса на первой береговой линии островов Дубай, сочетающий в себе комфорт, роскошный сервис, экологичность и инновации с особым акцентом на визуальную эстетику и гармонию. В инфраструктуру отеля входят бассейны, кафе, лаундж-зона, фитнес-зал и многое другое. Владельцы могут лично отдыхать или сдавать апартаменты в аренду, получая доход от 10% годовых.",
    id: "block1",
    pay: "рассрочка",
    benefit: "95 200 $",
    income: "28 560 $",
    btntitle: "Куда вам отправить презентацию ЖК NEXT CORAL?",
    btnsub: "Презентация ЖК NEXT CORAL",

    images: [
      "/images/Next coral/7.webp",
      "/images/Next coral/3.webp",
      "/images/Next coral/2.webp",
      "/images/Next coral/1.webp",
      "/images/Next coral/4.webp",
      "/images/Next coral/5.webp",
      "/images/Next coral/6.webp",
    ],
  },
  {
    title: "Апарт-отель Next white",
    class: "Люкс",
    category: `${georgia}`,
    noun: `${georgianoun}`,
    location: "Грузия, г. Батуми, ул. Шалвы Инасаридзе, 27",
    area: "32,2 – 101 м²",
    price: "57 000 $",
    about: "180 апартаментов",
    plan: "студии, 1, 2, 3 - комнатные",
    deadline: "сдан",
    sea: "150 м.",
    developer: "Next Group",
    description:
      "Бутик-отель премиум-класса с полноценным гостиничным обслуживанием и сервисами для комфортного отдыха и инвестиций. На территории расположены ресторан, лобби-бар, фитнес-центр, коворкинг, охрана и парковка. В пешей доступности находятся продуктовые магазины, кафе и остановки общественного транспорта. Дизайн апартаментов соответствуют отельным стандартам 5*.",
    id: "block1",
    pay: "рассрочка, ипотека",
    benefit: "20 520 $",
    income: "9 000 $",
    btntitle: "Куда вам отправить презентацию Апарт-отеля Next white?",
    btnsub: "Презентация Апарт-отеля Next white",

    images: [
      "/images/Next white/1.webp",
      "/images/Next white/2.webp",
      "/images/Next white/3.webp",
      "/images/Next white/4.webp",
      "/images/Next white/5.webp",
      "/images/Next white/6.webp",
      "/images/Next white/7.webp",
      "/images/Next white/8.webp",
      "/images/Next white/9.webp",
      "/images/Next white/10.webp",
      "/images/Next white/11.webp",
    ],
  },
  {
    title: "Жилой комплекс Sunshine Phuket",
    class: "Элитный",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    location: "Таиланд, Пхукет, Банг Тао",
    area: "29 - 60 м²",
    price: "от 190 000 $",
    about: "180 апартаментов",
    plan: "9 корпусов по 4 - 5 этажей, 672 квартиры",
    deadline: "сдан",
    sea: "50 м.",
    developer: "T.H. Group Phuket",
    description:
      "Комплекс расположен на роскошном пляже Банг Тао. Проект разделен на 2 части: инвестиционную и резиденцию. Инвестиционная часть находится под управлением 4* отельного оператора и предназначена для получения пассивного дохода, жилая часть для личного пользования и подойдет для отдыха. Инфраструктура включает в себя бассейн, ресторан, SPA- и фитнес-центры, детская комната, шаттл-бас.",
    id: "block1",
    pay: "рассрочка",
    benefit: "76 000 $",
    income: "13 300 $",
    btntitle: "Куда вам отправить презентацию ЖК Sunshine Phuket?",
    btnsub: "Презентация ЖК Sunshine Phuket",

    images: [
      "/images/Sunshine Phuket/5.webp",
      "/images/Sunshine Phuket/6.webp",
      "/images/Sunshine Phuket/7.webp",
      "/images/Sunshine Phuket/8.webp",
      "/images/Sunshine Phuket/9.webp",
      "/images/Sunshine Phuket/10.webp",
      "/images/Sunshine Phuket/11.webp",
      "/images/Sunshine Phuket/1.webp",
      "/images/Sunshine Phuket/2.webp",
      "/images/Sunshine Phuket/3.webp",
      "/images/Sunshine Phuket/4.webp",
    ],
  },
  {
    title: "Жилой комплекс VIP Space Odyssey",
    class: "Комфорт",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    location: "Таиланд, Пхукет, Раваи",
    area: "29 - 69 м²",
    price: "90 340 $",
    about: "1 здание, 8 этажей, 600 квартир",
    plan: "студии, 1, 2 - комнатные",
    deadline: "декабрь, 2028 г.",
    sea: "800 м.",
    developer: "Vip Thailand Development Company",
    description:
      "Равай привлекает любителей активного отдыха: здесь можно заняться дайвингом, сноркелингом и катанием на каяках. Каждое помещение оборудовано современными удобствами и имеет эстетически приятный вид, создавая атмосферу уюта и гармонии. На территории расположен современный фитнес-центр и 2 панорамных бассейна. Уже сейчас можно стать владельцем роскошной недвижимости в райском уголке.",
    id: "block1",
    pay: "рассрочка",
    benefit: "36 136 $",
    income: "13 550 $",
    btntitle: "Куда вам отправить презентацию ЖК VIP Space Odyssey?",
    btnsub: "Презентация  ЖК VIP Space Odyssey",

    images: [
      "/images/Space Odyssey/9.webp",
      "/images/Space Odyssey/6.webp",
      "/images/Space Odyssey/1.webp",
      "/images/Space Odyssey/2.webp",
      "/images/Space Odyssey/3.webp",
      "/images/Space Odyssey/4.webp",
      "/images/Space Odyssey/5.webp",
      "/images/Space Odyssey/7.webp",
      "/images/Space Odyssey/8.webp",
    ],
  },
  {
    title: "Отельный комплекс Montemar",
    category: `${georgia}`,
    noun: `${georgianoun}`,
    location: "Грузия, г. Батуми, шоссе Андрея Первозванного, 87г.",
    area: "32 - 162 м²",
    view: "море, горы",
    price: "64 935 $ до 545 715 $",
    about: "16 этажей",
    plan: "студии, 1, 2- комнатные",
    deadline: "4 квартал 2027 г.",
    sea: "100 м.",
    developer: "Gumbati Group",
    description:
      "Удачное расположение гарантирует не только прямой доступ на пляж, близость к горам и инфраструктуре, но и неповторимые панорамные виды. Рядом с комплексом имеются объекты торговой и развлекательной инфраструктуры, а также магазины, кафе, рестораны, АЗС.Инфраструктура комплекса включает в себя: бассейн, пляж, SPA- и фитнес-центр, рестораны, бары, коворкинг и деловой центр, казино.",
    id: "block1",
    pay: "рассрочка, ипотека",
    benefit: "40%",
    income: "9 900 $",
    btntitle: "Куда вам отправить презентацию Montemar?",
    btnsub: "Презентация Montemary",

    images: [
      "/images/Montemar/1.webp",
      "/images/Montemar/2.webp",
      "/images/Montemar/3.webp",
      "/images/Montemar/4.webp",
      "/images/Montemar/5.webp",
      "/images/Montemar/6.webp",
      "/images/Montemar/7.webp",
      "/images/Montemar/8.webp",
    ],
  },
  {
    title: "The Legend of Ubud",
    class: "Люкс",
    category: `${indonesia}`,
    noun: `${indonesianoun}`,
    location: "Индонезия, Бали, Убуд",
    area: "1 150 м²",
    view: "рисовые поля",
    price: "182 000 $",
    about: "5 зданий, 4 виллы и 1 инфраструктурное здание",
    deadline: "3 квартал 2025 г.",
    developer: "HIT Development",
    description:
      "Комплекс класса люкс расположен в самом сердце культурного центра Бали. Этот эксклюзивный участок окружён охраняемыми рисовыми полями. Каждая вилла занимает 1 150 м² и рассчитана на размещение до 10 гостей. Общая концепция сосредоточена на сочетании традиционного балийского дизайна с современными, экологически чистыми технологиями.",
    id: "block1",
    pay: "рассрочка",
    benefit: "74 620 $",
    income: "41 800 $",
    btntitle: "Куда вам отправить презентацию The Legend of Ubud?",
    btnsub: "Презентация The Legend of Ubud",

    images: [
      "/images/Legend of Ubud/12.webp",
      "/images/Legend of Ubud/9.webp",
      "/images/Legend of Ubud/10.webp",
      "/images/Legend of Ubud/11.webp",
      "/images/Legend of Ubud/1.webp",
      "/images/Legend of Ubud/2.webp",
      "/images/Legend of Ubud/3.webp",
      "/images/Legend of Ubud/4.webp",
      "/images/Legend of Ubud/5.webp",
      "/images/Legend of Ubud/6.webp",
      "/images/Legend of Ubud/7.webp",
      "/images/Legend of Ubud/8.webp",
    ],
  },
  {
    title: "Апарт-отель Geuz Towers",
    class: "Премиум",
    category: `${georgia}`,
    noun: `${georgianoun}`,
    location: "Грузия, г. Кобулети, просп. Давида Агмашенебели, 379",
    area: "32 - 205 м²",
    price: "74 806 $ до 449 817 $",
    about: "45 этажей, 1 278 апартаментов",
    deadline: "2 квартал 2028 г.",
    developer: "GEUZ Building",
    sea: "50 м.",
    description:
      "В непосредственной близости представлен полный спектр удобств, включая кафе, кофейни, бары, аптеки, магазины, супермаркеты, студии красоты, отели, стадион «Челе Арена», автомойки, АЗС, клинику Central Hospital, школу и детский сад. Инфраструктура отеля включает в себя 2 бассейна, 3 панорамных ресторана, кинотеатр, SPA- и фитнес-центры, аптека, банкоматы, коворкинг-центр, детская комната и кафе.",
    id: "block1",
    pay: "рассрочка, ипотека",
    benefit: "30 000 $",
    income: "7 480 $",
    btntitle: "Куда вам отправить презентацию Апарт-отеля Geuz Tower?",
    btnsub: "Презентация Апарт-отеля Geuz Tower",

    images: [
      "/images/Geuz Towers/4.webp",
      "/images/Geuz Towers/6.webp",
      "/images/Geuz Towers/1.webp",
      "/images/Geuz Towers/2.webp",
      "/images/Geuz Towers/3.webp",
      "/images/Geuz Towers/5.webp",
    ],
  },
  {
    title: "Жилой комплекс Platinum Bay",
    class: "Премиум",
    category: `${tailand}`,
    noun: `${tailandnoun}`,
    location: "Таиланд, Пхукет, Камала",
    area: "25 - 38 м²",
    price: "130 000 $",
    about: "14 зданий, 432 апартамента",
    deadline: "Сдан",
    developer: "New World ADM Platinum",
    sea: "200 м.",
    description:
      "ЖК окружен пляжами с чистейшими песчаными берегами протяженностью 1,5 км, идеальными для спокойного отдыха и созерцания потрясающих тропических закатов. Апартаменты оформлены в современном стиле с панорамными окнами, меблированы и оборудованы техникой. Часть из них имеет личный бассейн и балкон. Каждый юнит представлен просторной гостиной, кухней и балконом.",
    id: "block1",
    pay: "рассрочка",
    benefit: "52 000 $",
    income: "16 900 $",
    btntitle: "Куда вам отправить презентацию Апарт-отеля Platinum Bay?",
    btnsub: "Презентация Апарт-отеля Platinum Bay",

    images: [
      "/images/Platinum Bay/1.webp",
      "/images/Platinum Bay/2.webp",
      "/images/Platinum Bay/3.webp",
      "/images/Platinum Bay/4.webp",
      "/images/Platinum Bay/5.webp",
      "/images/Platinum Bay/6.webp",
      "/images/Platinum Bay/7.webp",
      "/images/Platinum Bay/8.webp",
      "/images/Platinum Bay/9.webp",
      "/images/Platinum Bay/10.webp",
      "/images/Platinum Bay/11.webp",
    ],
  },
  //новые
  {
    title: "Жилой комплекс Azizi Riviera",
    class: "Премиум",
    category: `${oae}`,
    noun: `${oae}`,
    location: "ОАЭ, Дубай, район Мейдан",
    area: "40 - 130 м²",
    price: "19 164 295 до 100 644 000 ₽",
    about: "10 корпусов, 300 апартаментов",
    plan: "1, 2, 3 - комнатные",
    deadline: "3 квартал 2026 г.",
    developer: "Azizi Developments",
    sea: "5 км",
    description:
      "Azizi Riviera — красивый,  масштабный комплекс, представляющий собой практически город в городе, известный как «копия Французской Ривьеры в Персидском заливе». На территории предусмотрены бассейны, прогулочные зоны и торговые галереи. Рядом находятся рестораны, фитнес-клубы и парки. Апартаменты с панорамными окнами созданы для тех, кто ценит высокий уровень комфорта",
    id: "block1",
    pay: "рассрочка",
    benefit: "3 832 859 ₽ до 20 128 800 ₽",
    income: "1 149 857 ₽",
    btntitle: "Куда вам отправить презентацию ЖК Azizi Riviera?",
    btnsub: "Презентация ЖК Azizi Riviera",

    images: [
      "/images/Azizi Riviera/1.webp",
      "/images/Azizi Riviera/2.webp",
      "/images/Azizi Riviera/3.webp",
      "/images/Azizi Riviera/4.webp",
      "/images/Azizi Riviera/5.webp",
      "/images/Azizi Riviera/6.webp",
      "/images/Azizi Riviera/7.webp",
    ],
  },
  {
    title: "Жилой комплекс Hartland Greens",
    class: "Премиум",
    category: `${oae}`,
    noun: `${oae}`,
    location: "ОАЭ, Дубай, район Собха Хартленд",
    area: "от 45- 215 м²",
    price: "27 408 000 ₽",
    about: "6 корпусов, 250 апартаментов",
    plan: "1, 2, 3 - комнатные",
    deadline: "2 квартал 2026 г.",
    developer: "Sobha Realty",
    sea: "6 км",
    description:
      "Элитный жилой комплекс с видами на зеленые парки и водные каналы. На территории расположены бассейны, фитнес-центры и прогулочные зоны. Рядом находятся ТЦ, рестораны и школы. К 2030 году запланировано открытие станций метро в районе, что повлечет за собой рост спроса на аренду и покупку недвижимости.",
    id: "block1",
    pay: "рассрочка",
    benefit: "5 481 600 ₽",
    income: "1 644 480 ₽",
    btntitle: "Куда вам отправить презентацию ЖК Hartland Greens?",
    btnsub: "Презентация ЖК Hartland Greens",

    images: [
      "/images/Hartland Greens/1.webp",
      "/images/Hartland Greens/2.webp",
      "/images/Hartland Greens/3.webp",
      "/images/Hartland Greens/4.webp",
      "/images/Hartland Greens/5.webp",
      "/images/Hartland Greens/6.webp",
      "/images/Hartland Greens/7.webp",
      "/images/Hartland Greens/8.webp",
      "/images/Hartland Greens/9.webp",
    ],
  },
  {
    title: "Жилой комплекс Emaar South Golf Views",
    class: "Премиум",
    category: `${oae}`,
    noun: `${oae}`,
    location: "ОАЭ, Дубай, район Южный Дубай",
    area: "60 - 240 м²",
    price: "16 350 881 ₽",
    about: "7 корпусов, 280 апартаментов",
    plan: "1, 2, 3 - комнатные",
    deadline: "3 квартал 2026 г.",
    developer: "Emaar Properties",
    sea: "6 км",
    description:
      "Роскошный жилой комплекс с видами на гольф-поля и зеленые парки. На территории есть бассейны, спортивные площадки и торговые зоны. Рядом расположены рестораны и школы. Выгода от инвестиций до 30% благодаря росту стоимости после завершения. Идеально для тех, кто ищет комфорт и стиль в престижном районе.",
    id: "block1",
    pay: "рассрочка",
    benefit: "3 270 176 ₽",
    income: "981 052 ₽",
    btntitle: "Куда вам отправить презентацию ЖК Emaar South Golf Views?",
    btnsub: "Презентация ЖК Emaar South Golf Views",

    images: [
      "/images/Emaar South Golf Views/1.webp",
      "/images/Emaar South Golf Views/2.webp",
      "/images/Emaar South Golf Views/3.webp",
      "/images/Emaar South Golf Views/4.webp",
      "/images/Emaar South Golf Views/5.webp",
      "/images/Emaar South Golf Views/6.webp",
      "/images/Emaar South Golf Views/7.webp",
    ],
  },
  {
    title: "VIDA Residences Dubai Marina",
    class: "Премиум",
    category: `${oae}`,
    noun: `${oae}`,
    location: "ОАЭ, Дубай, район Даунтаун",
    area: "76 - 193 м²",
    price: "66 236 000 ₽",
    about: "57 этажей, 158 номеров",
    plan: "1, 2, 3 - комнатные",
    deadline: "1 квартал 2026 г.",
    developer: "Emaar Properties",
    sea: "5 минут",
    description:
      "Каждые отдельные апартаменты – образец изысканного и продуманного интерьера, где сочетается современный дизайн, стильная отделка и тщательно подобранная цветовая гамма. Располагаясь на набережной искусственного залива, Dubai Residences предлагает жителям быстрый и беспрепятственный доступ к лучшей инфраструктуре Дубая.",
    id: "block1",
    pay: "рассрочка",
    benefit: "16 559 000 ₽",
    income: "5 298 880 ₽",
    btntitle: "Куда вам отправить презентацию VIDA Residences Dubai Marina?",
    btnsub: "Презентация VIDA Residences Dubai Marina",

    images: [
      "/images/Vida residences/1.webp",
      "/images/Vida residences/2.webp",
      "/images/Vida residences/3.webp",
      "/images/Vida residences/4.webp",
      "/images/Vida residences/5.webp",
      "/images/Vida residences/6.webp",
    ],
  },
  {
    title: "Creek Horizon",
    class: "Премиум",
    category: `${oae}`,
    noun: `${oae}`,
    location: "ОАЭ, Дубай, район Крик Харбор",
    area: "35 - 160 м²",
    price: "14 861 764 ₽ до 103 378 162 ₽",
    about: "2 здания",
    plan: "студии, 1, 2, 3 - комнатные",
    deadline: "Сдан",
    developer: "Emaar Properties",
    sea: "6 км",
    description:
      "В комплексе представлены апартаменты с большим многообразием площадей и планировок. В каждом жилом пространстве выполнена детальная отделка, а большие окна и балконы обеспечивают широкий обзор на бухту Dubai Creek, пристань для яхт и башню Бурдж‑Халифа.",
    id: "block1",
    pay: "рассрочка",
    benefit: "4 458 529 ₽",
    income: "1 337 558 ₽",
    btntitle: "Куда вам отправить презентацию Creek Horizon?",
    btnsub: "Презентация Creek Horizon",

    images: [
      "/images/Creek Horizon/1.webp",
      "/images/Creek Horizon/2.webp",
      "/images/Creek Horizon/3.webp",
      "/images/Creek Horizon/4.webp",
      "/images/Creek Horizon/5.webp",
      "/images/Creek Horizon/6.webp",
    ],
  },

  {
    title: "Yekta Kingdom Premium",
    class: "Премиум",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Аланья, район Махмутлар",
    area: "63-175 м²",
    price: "от 12 628 000 - 25 257,000 ₽",
    about: "5 корпусов, 12 этажей, 720 апартаментов",
    plan: "1, 2, 3 - комнатные",
    deadline: "Декабрь 2024 г.",
    developer: "Yekta Homes",
    sea: "550 м",
    description:
      "Элитный ЖК расположен на побережье Средиземного моря, в самой теплой части Турции. Расположение проекта соответствует статусу премиального жилого комплекса: небольшая удаленность от моря, близость к центру города и наличие поблизости супермаркетов, аптек, банков, кафе и социальных объектов.",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 025 000 ₽",
    income: "1 080 000 ₽",
    btntitle: "Куда вам отправить презентацию Yekta Kingdom Premium?",
    btnsub: "Презентация Yekta Kingdom Premium",

    images: [
      "/images/Yekta Kingdom Premium/1.webp",
      "/images/Yekta Kingdom Premium/2.webp",
      "/images/Yekta Kingdom Premium/3.webp",
      "/images/Yekta Kingdom Premium/4.webp",
    ],
  },

  {
    title: "Sea Pearl Ataköy",
    class: "Элитный",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Стамбул, район Атакёй",
    area: "от 88 - 398 м²",
    price: "от 45,000,000 ₽",
    about: "4 корпуса, 20 этажей, 631 квартира",
    plan: "1, 2, 3, 4 - комнатные",
    deadline: "Сдан",
    developer: "Kuzu Grup",
    sea: "50 м",
    description:
      "Благодаря своему расположению, социальным пространствам, усеянным привилегиями, и архитектуре, переосмысливающей концепцию роскоши, SeaPearl Ataköy был построен с качеством, которое сделает себе имя на долгие годы.",
    id: "block1",
    pay: "рассрочка",
    benefit: "9 000 000 ₽",
    income: "3 600 000 ₽",
    btntitle: "Куда вам отправить презентацию Sea Pearl Ataköy?",
    btnsub: "Презентация Sea Pearl Ataköy",

    images: [
      "/images/Sea Pearl Atakoy/1.webp",
      "/images/Sea Pearl Atakoy/2.webp",
      "/images/Sea Pearl Atakoy/3.webp",
      "/images/Sea Pearl Atakoy/4.webp",
      "/images/Sea Pearl Atakoy/5.webp",
      "/images/Sea Pearl Atakoy/6.webp",
      "/images/Sea Pearl Atakoy/7.webp",
      "/images/Sea Pearl Atakoy/8.webp",
      "/images/Sea Pearl Atakoy/9.webp",
    ],
  },

  {
    title: "Novus Sky",
    class: "Премиум",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Аланья, район Махмутлар",
    area: "от 57 - 216 м²",
    price: "от 13 851 000 ₽",
    about: "2 здания, 12 этажей, по 46 квартир",
    plan: "1, 2, 4 - комнатные, пентхаусы",
    deadline: "2 квартал 2025 г.",
    developer: "Novus Group",
    sea: "150 м",
    description: "Открытый и крытый бассейны, сауна, тренажерный зал",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 917 944 ₽",
    income: "1 750 766 ₽",
    btntitle: "Куда вам отправить презентацию Novus Sky?",
    btnsub: "Презентация Novus Sky",

    images: [
      "/images/Novus Sky/1.webp",
      "/images/Novus Sky/2.webp",
      "/images/Novus Sky/3.webp",
      "/images/Novus Sky/4.webp",
      "/images/Novus Sky/5.webp",
      "/images/Novus Sky/6.webp",
    ],
  },
  {
    title: "Elite Life 8",
    class: "Комфорт+",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Аланья, Каргыджак",
    area: "от 55 - 145 м²",
    price: "от 14 682 202 ₽",
    about: "5 этажей",
    plan: "1, 2 - комнатные",
    deadline: "Есть сданные",
    developer: "Elite Group",
    sea: "300 м",
    description:
      "ЖК строится в районе Kargıcak. Жильё подойдёт для семей с детьми — рядом несколько школ, детских садиков, парков, спортивных площадок; море в 15 минутах ходьбы. Инфраструктура комплекса: взрослый и детский бассейн, мини-клуб, тренажёрный зал с сауной, спа-центр.",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 936 440 ₽",
    income: "1 761 864 ₽",
    btntitle: "Куда вам отправить презентацию Elite Life 8?",
    btnsub: "Презентация Elite Life 8",

    images: [
      "/images/Elite Life 8/1.webp",
      "/images/Elite Life 8/2.webp",
      "/images/Elite Life 8/3.webp",
      "/images/Elite Life 8/4.webp",
      "/images/Elite Life 8/5.webp",
      "/images/Elite Life 8/6.webp",
      "/images/Elite Life 8/7.webp",
    ],
  },
  {
    title: "Yekta Blue V Residence",
    class: "Премиум",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Аланья, район Махмутлар",
    area: "от 45 - 176 м²",
    price: "от 14 682 060 ₽",
    about: "3 корпуса, 12 этажей, 168 квартир",
    plan: "1, 2, 3 - комнатные",
    deadline: "2 квартал 2025 г.",
    developer: "Yekta Homes",
    sea: "400 м",
    description:
      "Рядом со зданиями есть бассейны, тренажерные залы, оздоровительные центры, магазины, рестораны, кинотеатры, парки и сады, а также школы, больницы, аптеки и другие важные социальные объекты. Все резиденции имеют полную чистовую отделку.",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 936 440 ₽",
    income: "1 174 564 ₽",
    btntitle: "Куда вам отправить презентацию Yekta Blue V Residence?",
    btnsub: "Презентация Yekta Blue V Residence",

    images: [
      "/images/Yekta Blue V Residence/1.webp",
      "/images/Yekta Blue V Residence/2.webp",
      "/images/Yekta Blue V Residence/3.webp",
      "/images/Yekta Blue V Residence/4.webp",
    ],
  },
  {
    title: "Sinpaş Marina Ankara",
    class: "Премиум",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Анкара, район Оран",
    area: "от 70 - 200 м²",
    price: "от 16,838,000 ₽",
    about: "3 корпуса, 916 квартир",
    plan: "1, 2, 3 - комнатные",
    deadline: "Июнь 2025 г.",
    developer: "Sinpaş GYO",
    description:
      "Это единственный жилой проект, прилегающий к проекту канала Анкара, что придает ему большую инвестиционную ценность. Уникальный проект в столице для комфортной жизни и инвестиций с высоким потенциалом роста.",
    id: "block1",
    pay: "рассрочка",
    benefit: "2 525 700 ₽",
    income: "1 347 040 ₽",
    btntitle: "Куда вам отправить презентацию Sinpaş Marina Ankara?",
    btnsub: "Презентация Sinpaş Marina Ankara",

    images: [
      "/images/Sinpas Marina Ankara/1.webp",
      "/images/Sinpas Marina Ankara/2.webp",
      "/images/Sinpas Marina Ankara/3.webp",
      "/images/Sinpas Marina Ankara/4.webp",
      "/images/Sinpas Marina Ankara/5.webp",
      "/images/Sinpas Marina Ankara/6.webp",
      "/images/Sinpas Marina Ankara/7.webp",
      "/images/Sinpas Marina Ankara/8.webp",
      "/images/Sinpas Marina Ankara/9.webp",
    ],
  },
  {
    title: "Euro Residence 22",
    class: "Комфорт+",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Аланья, район Оба",
    area: "от 60 - 140 м²",
    price: "от 10 941 070 ₽",
    about: "1 здание, 85 апартамента",
    plan: "1, 2, 3 - комнатные, пентхаусы",
    deadline: "2025 г.",
    sea: "100 м",
    developer: "KURTSAFIR",
    description:
      "Учитывая идеальное местоположение, абсолютно из всех апартаментов открывается потрясающий вид Средиземного моря, города и старинной крепости Аланьи. Здесь продумано всё до мельчайших деталей — это больше, чем квартира на побережье, это инвестиция в высококачественный уровень жизни.",
    id: "block1",
    pay: "рассрочка",
    benefit: "1 641 160 ₽",
    income: "875 286 ₽",
    btntitle: "Куда вам отправить презентацию Euro Residence 22?",
    btnsub: "Презентация Euro Residence 22",

    images: [
      "/images/Euro Residence 22/1.webp",
      "/images/Euro Residence 22/2.webp",
      "/images/Euro Residence 22/3.webp",
      "/images/Euro Residence 22/4.webp",
      "/images/Euro Residence 22/5.webp",
      "/images/Euro Residence 22/6.webp",
      "/images/Euro Residence 22/7.webp",
      "/images/Euro Residence 22/8.webp",
      "/images/Euro Residence 22/9.webp",
      "/images/Euro Residence 22/10.webp",
      "/images/Euro Residence 22/11.webp",
    ],
  },
  {
    title: "Rams Beyond",
    class: "Премиум",
    category: `${tyrkey}`,
    noun: `${tyrkeynoun}`,
    location: "Турция, Стамбул, район Маслак",
    area: "от 79 - 295 м²",
    price: "от 25 257 000 ₽",
    about: "1 здание, 524 квартиры",
    plan: "1, 2, 3 - комнатные",
    deadline: "2025 г.",
    sea: "5 км",
    developer: "Rams Global",
    description:
      "В комплексе расположатся торговый центр, офисы, зал для фитнеса, 6-этажная парковка, рестораны, бассейны и вертолетная площадка на крыше. Из панорамных окон здания открываются виды на Босфор и леса.",
    id: "block1",
    pay: "рассрочка",
    benefit: "5 051 400 ₽",
    income: "3 030 840 ₽",
    btntitle: "Куда вам отправить презентацию Rams Beyond?",
    btnsub: "Презентация Rams Beyond",

    images: [
      "/images/Rams Beyond/1.webp",
      "/images/Rams Beyond/2.webp",
      "/images/Rams Beyond/3.webp",
      "/images/Rams Beyond/4.webp",
      "/images/Rams Beyond/5.webp",
      "/images/Rams Beyond/6.webp",
      "/images/Rams Beyond/7.webp",
      "/images/Rams Beyond/8.webp",
    ],
  },
];

export default cardsData;
