const cardsData = [
  {
    title: "Жилой комплекс Riviera Santa Monica",
    class: "Премиум",
    location: "Таиланд, Паттайя, Джомтьен",
    category: "Тайланд",
    noun: "Тайланде",
    area: "29 - 325 м²",
    price: "62 000 $",
    about: "34 этажа, 446 квартиры",
    plan: "1, 2, 3 - комнатные, пентхаусы",
    deadline: "2025-2028",
    sea: "1 км",
    developer: "The Riviera Group Thailand",
    description:
      "Комплекс расположен в престижном районе с развитой и близостью к пляжу, а из окон открываются виды на море. Удобное расположение: всего в нескольких минутах езды до пляжа, ключевых объектов инфраструктуры и рядом с основными дорожными развязками. Комплекс идеально подходит как для комфортного отдыха, так и для инвестиций - сдачи в аренду или перепродажи",
    id: "block1",
    pay: "рассрочка",
    benefit: "24%",
    income: "5 400 $",
    btntitle: "Куда вам отправить презентацию The Riviera Santa Monica?",
    btnsub: "Презентация The Riviera Santa Monica",
    images: [
      "./images/RivetaSantaMonica/RivieraSantaMonica1.webp",
      "./images/RivetaSantaMonica/RivieraSantaMonica3.webp",
      "./images/RivetaSantaMonica/RivieraSantaMonica4.webp",
      "./images/RivetaSantaMonica/RivieraSantaMonica5.webp",
    ],
  },
  {
    title: "Гостиничный комплекс Нескучный сад",
    class: "Премиум",
    category: "Россия",
    noun: "России",
    location: "Россия, Краснодарский край, г. Сочи",
    area: "22 м² - 136 м²",
    price: "26 200 000 ₽",
    about: "5 корпусов, 407 номеров",
    plan: "студии, 1, 2, 3, 4 - комнатные",
    deadline: "2025",
    sea: "500 м",
    developer: "ООО СЗ ЗЕЛЕНАЯ ГОРКА",
    description:
      "ГК премиум-класса создан специально для тех, кто ценит уединение и высокий уровень комфорта. Инфраструктура комплекса удивляет: зона  проживания и перспективный инвестиционный актив.",
    declaration: "https://наш.дом.рф/",
    id: "block2",
    pay: "ипотека, рассрочка",
    benefit: "55%",
    income: "180 000 ₽",
    btntitle:
      "Куда вам отправить презентацию гостиничного комплекса Нескучный сад?",
    btnsub: "Презентация гостиничного комплекса Нескучный сад",

    images: [
      "/images/neskuchny_garden/1.webp",
      "/images/neskuchny_garden/2.webp",
      "/images/neskuchny_garden/3.webp",
      "/images/neskuchny_garden/4.webp",
      "/images/neskuchny_garden/5.webp",
      "/images/neskuchny_garden/6.webp",
      "/images/neskuchny_garden/7.webp",
    ],
  },
  {
    title: "Гостиничный комплекс LIVINGSTON",
    class: "Премиум",
    category: "Россия",
    noun: "России",
    location: "Россия, Краснодарский край, г. Сочи",
    area: "от 18 - 187 м²",
    price: "15 920 000 ₽",
    about: "888 номеров",
    plan: "студии, 1, 2, 3 - комнатные",
    deadline: "2 квартал 2026 г",
    sea: "5 мин",
    developer: "ООО «СочиОйлСтрой»",
    description:
      "ГК «Livingstone» располагается в туристическом сердце города — микрорайоне Мамайка, который давно полюбился гостям и жителям города. Экологически чистый район с богатой инфраструктурой и  близостью к морю. Прогулка в LIVINGSTON к морю по живописному парку займет всего 5 минут. Окружённый тенью деревьев, широкий и чистый, с удобным входом в воду, пляж у отеля подарит уединение и гармонию с природой.",
    declaration: "https://наш.дом.рф/",
    id: "block2",
    pay: "ипотека, рассрочка",
    benefit: "40%",
    income: "3 750 000 ₽",
    btntitle:
      "Куда вам отправить презентацию гостиничного комплекса LIVINGSTON?",
    btnsub: "Презентация гостиничного комплекса LIVINGSTON",

    images: [
      "/images/LIVINGSTON/1.webp",
      "/images/LIVINGSTON/2.webp",
      "/images/LIVINGSTON/3.webp",
      "/images/LIVINGSTON/4.webp",
      "/images/LIVINGSTON/5.webp",
      "/images/LIVINGSTON/6.webp",
    ],
  },

  {
    title: "Жилой комплекс Ozdence Hill Luxury Residence",
    class: "Премиум",
    category: "Турция",
    noun: "Турции",
    location: "Турция, Алания, Каргыджак",
    area: "от 69 - 491 м²",
    price: "310 000 $",
    about: "138 квартир",
    plan: "студии, 1, 2, 3, 4 - комнатные",
    deadline: "2 квартал 2026 г",
    developer: "OZDENCE GROUP",
    description:
      "Özdence Hill Luxury Residence — это роскошный жилой комплекс, который предлагает своим собственникам широкий спектр удобств и возможностей для комфортного проживания. В резиденции расположенытеннисные и баскетбольные площадки, мини-гольф, бассейн с водным парком, рестораны и бары высокого класса.",
    id: "block2",
    pay: "рассрочка",
    benefit: "30%",
    income: "22 400 €",
    btntitle: "Куда вам отправить презентацию Ozdence Hill Luxury Residence?",
    btnsub: "Презентация Ozdence Hill Luxury Residence",

    images: [
      "/images/Ozdence/0.webp",
      "/images/Ozdence/1.webp",
      "/images/Ozdence/2.webp",
      "/images/Ozdence/3.webp",
      "/images/Ozdence/4.webp",
      "/images/Ozdence/5.webp",
    ],
  },
  {
    title: "Гостиничный комплекс Royal Beach Resort & Spa",
    class: "Бизнес",
    category: "Россия",
    noun: "России",
    location: "Россия, г. Сочи, Лазаревский р-н, п. Аше",
    area: "номера от 19 - 75 м², резиденции от 52 - 148 м²",
    price: "8 400 000 ₽",
    about: "408 номеров",
    plan: "студии, 1, 2 - комнатные",
    deadline: "2027 г",
    sea: "150 м.",
    developer: "ООО «Еврострой»",
    declaration: "https://наш.дом.рф/",
    description:
      "Royal Beach Sochi расположен на территории 10 га. Инфраструктура  отеля включает в себя деловые и развлекательные зоны, детские испортивные площадки, SPA, кафе и рестораны, бассейны, пляж и др.Royal Beach Sochi – это не только прекрасное место для отдыха, но и отличная инвестиционная возможность. Программа доверительного управления обеспечивает качественный сервис и гарантирует стабильный арендный доход.",
    id: "block3",
    pay: "рассрочка, ипотека",
    benefit: "2 900 000 ₽",
    income: "3 300 000 ₽",
    btntitle: "Куда вам отправить презентацию Royal Beach Resort & Spa?",
    btnsub: "Презентация Royal Beach Resort & Spa",

    images: [
      "/images/Royal Beach/1.webp",
      "/images/Royal Beach/2.webp",
      "/images/Royal Beach/3.webp",
      "/images/Royal Beach/4.webp",
      "/images/Royal Beach/5.webp",
      "/images/Royal Beach/6.webp",
      "/images/Royal Beach/7.webp",
      "/images/Royal Beach/8.webp",
      "/images/Royal Beach/9.webp",
      "/images/Royal Beach/10.webp",
      "/images/Royal Beach/11.webp",
      "/images/Royal Beach/12.webp",
    ],
  },
  {
    title: "Гостиничный комплекс Naiman Residence",
    class: "Премиум",
    category: "Россия",
    noun: "России",
    location: "г. Сочи, Курортный проспект",
    area: "24 - 74 м²",
    price: "31 400 000 ₽",
    about: "4 корпуса, 7 этажей, 867 апартаментов",
    plan: "студии, 1, 2- комнатные",
    deadline: "2026г, есть сданные",
    sea: "400 м.",
    developer: "ООО Альпика",
    declaration: "https://наш.дом.рф/",
    description:
      "Комплекс Naiman Residence - это перспективная инвестиция с потенциалом высокой доходности. Расположение вблизи моря и гор делает его привлекательным для арендаторов круглый год. Современная инфраструктура включает бассейны, фитнес-центры и зоны отдыха. Рынок недвижимости Сочи показывает устойчивый рост, что увеличивает стоимость квартир.",
    id: "block1",
    pay: "рассрочка, ипотека",
    benefit: "12 560 000 ₽",
    income: "8 400 000 ₽",
    btntitle: "Куда вам отправить презентацию Naiman Residence?",
    btnsub: "Презентация Naiman Residence",

    images: [
      "/images/Naiman Residence/1.webp",
      "/images/Naiman Residence/2.webp",
      "/images/Naiman Residence/3.webp",
      "/images/Naiman Residence/4.webp",
      "/images/Naiman Residence/5.webp",
      "/images/Naiman Residence/6.webp",
      "/images/Naiman Residence/7.webp",
      "/images/Naiman Residence/8.webp",
      "/imagesNaiman Residence/9.webp",
      "/images/Naiman Residence/10.webp",
      "/images/Naiman Residence/11.webp",
    ],
  },
  {
    title: "Жилой комплекс Кислород",
    class: "Бизнес",
    category: "Россия",
    noun: "России",
    location: "Россия, г. Сочи, ул. Ясногорская",
    area: "17,8 - 66,12 м²",
    price: "8 400 000 ₽",
    about: "15 корпусов, 20 этажей",
    plan: "студии, 1, 2, 3 - комнатные",
    deadline: "1–4 квартал 2025, есть сданные",
    sea: "1,5 км",
    developer: "ООО СЗ КИСЛОРОД",
    declaration: "https://наш.дом.рф/",
    description:
      "Расположение ЖК в экологически чистом районе, недалеко от побережья Черного моря, создаёт высокий спрос на аренду и покупку жилья. Современная архитектура и качественные строительные материалы делают этот проект надежным вложением. Развитая инфраструктура, включающая зеленые зоны, спортивные площадки, рестораны и коммерческие объекты, повышает привлекательность комплекса",
    id: "block3",
    pay: "ипотека",
    benefit: "от 900 000 ₽",
    income: "1 100 000 ₽",
    btntitle: "Куда вам отправить презентацию жилого комплекса Кислород?",
    btnsub: "Презентация жилого комплекса Кислород",

    images: [
      "/images/Oxyden/2.webp",
      "/images/Oxyden/1.webp",
      "/images/Oxyden/3.webp",
      "/images/Oxyden/4.webp",
      "/images/Oxyden/5.webp",
      "/images/Oxyden/6.webp",
      "/images/Oxyden/7.webp",
      "/images/Oxyden/8.webp",
      "/images/Oxyden/9.webp",
      "/images/Oxyden/10.webp",
      "/images/Oxyden/12.webp",
    ],
  },
  {
    title: "Гостиничный комплекс Naiman Residence",
    class: "Премиум",
    category: "Россия",
    noun: "России",
    location: "г. Сочи, Курортный проспект",
    area: "24 - 74 м²",
    price: "31 400 000 ₽",
    about: "4 корпуса, 7 этажей, 867 апартаментов",
    plan: "студии, 1, 2- комнатные",
    deadline: "2026г, есть сданные",
    sea: "400 м.",
    developer: "ООО Альпика",
    declaration: "https://наш.дом.рф/",
    description:
      "Комплекс Naiman Residence - это перспективная инвестиция с потенциалом высокой доходности. Расположение вблизи моря и гор делает его привлекательным для арендаторов круглый год. Современная инфраструктура включает бассейны, фитнес-центры и зоны отдыха. Рынок недвижимости Сочи показывает устойчивый рост, что увеличивает стоимость квартир.",
    id: "block1",
    pay: "рассрочка, ипотека",
    benefit: "12 560 000 ₽",
    income: "8 400 000 ₽",
    btntitle: "Куда вам отправить презентацию Naiman Residence?",
    btnsub: "Презентация Naiman Residence",

    images: [
      "/images/Naiman Residence/1.webp",
      "/images/Naiman Residence/2.webp",
      "/images/Naiman Residence/3.webp",
      "/images/Naiman Residence/4.webp",
      "/images/Naiman Residence/5.webp",
      "/images/Naiman Residence/6.webp",
      "/images/Naiman Residence/7.webp",
      "/images/Naiman Residence/8.webp",
      "/imagesNaiman Residence/9.webp",
      "/images/Naiman Residence/10.webp",
      "/images/Naiman Residence/11.webp",
    ],
  },

  {
    title: "Отель Angsana Oceanview Residences",
    class: "Люкс",
    category: "Тайланд",
    noun: "Тайланде",
    location: "Таиланд, Пхукет, Чернгталай",
    area: "209 - 395 м²",
    price: "1 300 000 $",
    about: "3 здания, 7 этажей, 149 квартир",
    plan: "2, 3 - комнатные, апартаменты",
    deadline: "2025г., есть сданные",
    sea: "800 м.",
    developer: "Laguna Property",
    description:
      "Каждое жильё оснащено бассейном с захватывающими видами на озеро и пляж. В резиденциях есть гостиная, спальня с ванной и выходом на террасу. В пентхаусах на нижнем уровне жилые помещения, а на верхнем большая развлекательная терраса и бассейн. Удобства и инфраструктура: SPA- и фитнес-центр, ресторан и бар, прямой доступ к пляжу. Покупатели получают право пользования апартаментами.",
    id: "block1",
    pay: "рассрочка",
    benefit: "522 000 $",
    income: "130 565 $",
    btntitle: "Куда вам отправить презентацию Angsana Oceanview Residences?",
    btnsub: "Презентация Angsana Oceanview Residences",

    images: [
      "/images/Angsana/1.webp",
      "/images/Angsana/2.webp",
      "/images/Angsana/3.webp",
      "/images/Angsana/4.webp",
      "/images/Angsana/5.webp",
      "/images/Angsana/6.webp",
      "/images/Angsana/7.webp",
      "/images/Angsana/8.webp",
      "/images/Angsana/9.webp",
    ],
  },
  /*
  {
    title: "Гостиничный комплекс WYNDHAM Sochi 5",
    class: "Премиум",
    category: "Россия",
    noun: "России",
    location: "г. Сочи, Курортный проспект",
    area: "24 - 74 м²",
    price: "31 400 000 ₽",
    about: "4 корпуса, 7 этажей, 867 апартаментов",
    plan: "студии, 1, 2- комнатные",
    deadline: "2026г, есть сданные",
    sea: "400 м.",
    developer: "ООО Альпика",
    declaration: "https://наш.дом.рф/",
    description:
      "Комплекс Naiman Residence - это перспективная инвестиция с потенциалом высокой доходности. Расположение вблизи моря и гор делает его привлекательным для арендаторов круглый год. Современная инфраструктура включает бассейны, фитнес-центры и зоны отдыха. Рынок недвижимости Сочи показывает устойчивый рост, что увеличивает стоимость квартир.",
    id: "block1",
    pay: "рассрочка, ипотека",
    benefit: "12 560 000 ₽",
    income: "8 400 000 ₽",
    btntitle: "Куда вам отправить презентацию Naiman Residence?",
    btnsub: "Презентация Naiman Residence",

    images: [
      "/images/Naiman Residence/1.webp",
      "/images/Naiman Residence/2.webp",
      "/images/Naiman Residence/3.webp",
      "/images/Naiman Residence/4.webp",
      "/images/Naiman Residence/5.webp",
      "/images/Naiman Residence/6.webp",
      "/images/Naiman Residence/7.webp",
      "/images/Naiman Residence/8.webp",
      "/imagesNaiman Residence/9.webp",
      "/images/Naiman Residence/10.webp",
      "/images/Naiman Residence/11.webp",
    ],
  },*/
];

export default cardsData;
